name: xianglemei
description: 想了莓 - 你的专属情对学停势停 下域或
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
environment:
  sdk: '^3.5.0'

flutter:
  uses-material-design: true